### ISSUE TITLE
`Int63` not implemented yet?

### ISSUE THREAD

**Issue by mro** [mirage/optint#12]
Hi @dinosaure, how is `Int63` supposed to be accessed?

I learned about it from @CraigFe in https://discuss.ocaml.org/t/advantage-of-int63-compared-to-int64/7465 but can't find it here.

**Comment by dinosaure** [comment]
Hi,

Due to retro-compatibility reasons, the `Int63` module is _unwrapped_ and accessible _at top_:
```sh
$ opam install optint.0.0.5
$ cat >dune <<EOF
(executable (name main) (libraries optint))
EOF
$ cat >main.ml <<EOF
let () = Format.printf "%a\n%!" Int63.pp Int63.zero
EOF
$ dune exec -- ./main.exe
```

So you should be able to use directly with `Int63`. Note that the module can be shadowed by an `open` of another library which provides the same module name such as `base`.

EDIT: add an explicit version on `optint`

**Comment by mro** [comment]
maybe that doesn't work with my static/musl switch?

```
bash-3.2$ cat >dune <<EOF
> (executable (name main) (libraries optint))
> EOF
bash-3.2$ cat >main.ml <<EOF
> let () = Format.printf "%a\n%!" Int63.pp Int63.zero
> EOF
bash-3.2$ dune exec -- ./main.exe
Info: Creating file dune-project with this contents:
| (lang dune 2.8)
File "main.ml", line 1, characters 32-40:
1 | let () = Format.printf "%a\n%!" Int63.pp Int63.zero
                                    ^^^^^^^^
Error: Unbound module Int63
Hint: Did you mean Int64?
bash-3.2$ opam switch
#  switch   compiler                    description
→  default  ocaml-base-compiler.4.10.2  default
bash-3.2$ uname -sm
Darwin arm64

and also

bash-3.2$ opam switch
opam switch
#  switch                      compiler                                   description
   4.10.0                      ocaml-base-compiler.4.10.0                 4.10.0
→  4.10.0+musl+static+flambda  ocaml-variants.4.10.0+musl+static+flambda  4.10.0+musl+static+flambda
   default                     ocaml-system.4.05.0                        default
bash-3.2$ uname -sm
Linux x86_64
```

**Comment by dinosaure** [comment]
Are you sure about the version of `optint` (`0.0.5`)? I just tried with your context and I can not reproduce your error :confused:. You can check it with `opam show optint` or directly be sure to use `0.0.5` with `opam install optint.0.0.5`.

**Comment by mro** [comment]
yes I am - but the cpu is arm 64 (Apple silicon) - that may bypass the dune switch? Linux seems to work (but I only release on linux, develop on Mac, so I didn't reach that state of success)

**Comment by mro** [comment]
uh! Oh, indeed 0.0.4!

**Comment by mro** [comment]
@dinosaure thanks for now, I'm confused, th 0.0.5 is now present after a reinstall, before it was 0.0.4. I'll check in detail tomorrow.

**Comment by mro** [comment]
@dinosaure you where precisely right – the version < 0.0.5 was the culprit. I just didn't `opam update` prior installing a few days ago and checked the most recent version here at github but not on my machines. Uh.

Now things work perfectly on `Darwin arm64`, `Linux x86_64` and `Linux armv6l` (Raspi Zero!). Thank you for your quick response, patience and a nice little module!

**Comment by mro** [comment]
P.S.: I use it here: https://git.sr.ht/~mro/geohash/tree/int63/item/lib/calc.ml
